[package]
name = "cw-orch-starship"
version = "0.4.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Adapter for interacting with cosmoslogy:starship via cw-orch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.102"
ibc-chain-registry = { workspace = true }
ibc-relayer-types = { workspace = true }
thiserror = "1.0.43"
cosmwasm-std = "1.2.7"

cw-orch-daemon = { workspace = true }
cw-orch-core = { workspace = true }
tokio = { workspace = true }

url = "2.4.1"
log.workspace = true
